org: nibras39
app: flowerey
service: flowerey

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  graphql:
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: get
        cors: true
    - http:
        path: graphql
        method: post
        cors: true        
  hello:
    handler: handler.hello

resources:
  Resources:
    FlowerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-flowerTable-${sls:stage}
